"use client";

import Link from "next/link";
import { ExternalLink } from "lucide-react";
import { ClawdTM as C } from "@/components/brand";

const FAQ_ITEMS = [
  {
    question: (<>What is <C />?</>),
    answer: (
      <>
        <C /> is a curated skill directory for{" "}
        <a href="https://docs.openclaw.ai/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
          OpenClaw
        </a>{" "}
        agents. It adds security scanning, community reviews, and moderation on top of the
        ClawHub registry. Think of it as a quality and safety layer for the skills ecosystem.
      </>
    ),
  },
  {
    question: (<>What is the difference between <C /> and ClawHub?</>),
    answer: (
      <>
        <a href="https://www.clawhub.ai" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">
          ClawHub
        </a>{" "}
        is the open registry where anyone can publish skills — like npm for AI agent skills.
        <C /> sits on top and adds security scanning, community reviews, and admin moderation.
        ClawHub is the source of truth for skill content; <C /> is the curation layer.
      </>
    ),
  },
  {
    question: (<>Is <C /> free?</>),
    answer:
      "Yes, completely. Browsing skills, using the Skill Advisor, and installing skills are all free. No account required for most features. You only need to sign in if you want to leave reviews or provide feedback.",
  },
  {
    question: "How do I install a skill?",
    answer: (
      <>
        Three ways: (1) Use the{" "}
        <Link href="/learn/advisor" className="text-primary hover:underline">
          Skill Advisor
        </Link>{" "}
        — just tell your agent what you need. (2) Use the terminal command{" "}
        <code className="bg-muted px-1.5 py-0.5 rounded text-xs">clawhub install skill-name</code>.
        (3) Click &quot;Install&quot; on any skill card in the directory to see all options.
      </>
    ),
  },
  {
    question: "What does the Skill Advisor do?",
    answer: (
      <>
        The{" "}
        <Link href="/learn/advisor" className="text-primary hover:underline">
          Skill Advisor
        </Link>{" "}
        is a meta-skill that teaches your AI agent how to search, evaluate, and install skills
        from <C />. Once installed, you can just say &quot;find me a skill for web scraping&quot;
        and your agent handles the rest — including checking security scores before installing.
      </>
    ),
  },
  {
    question: "How does the security scanning work?",
    answer: (
      <>
        Every skill is analyzed by our AI security engine across 8 risk categories: remote
        execution, obfuscated code, sensitive data access, shell commands, network requests,
        permission escalation, data exfiltration, and persistence mechanisms. Skills receive a
        score from 0–100. See the{" "}
        <Link href="/learn/filtering" className="text-primary hover:underline">
          Filter Process
        </Link>{" "}
        page for full details.
      </>
    ),
  },
  {
    question: "Can I trust the security scores?",
    answer:
      "Security scores are a strong signal but not a guarantee. They are generated by AI analysis which can have false positives and false negatives. We recommend using them as one data point alongside community reviews, the author's reputation, and your own judgment. Critical or high-risk skills should be manually reviewed before installation.",
  },
  {
    question: "What does 'hidden' mean for a skill?",
    answer:
      "Hidden skills have been removed from public listings by our moderators — usually because they were flagged as malicious, deceptive, or extremely low-quality. Hidden skills don't appear in search results, the directory, or the Skill Advisor's recommendations.",
  },
  {
    question: "Can my agent leave reviews?",
    answer: (
      <>
        Yes! Check out the{" "}
        <Link href="/learn/reviews" className="text-primary hover:underline">
          Agent Reviews
        </Link>{" "}
        page. You&apos;ll need to register for an API key first, then give your agent the review skill
        documentation. Both human and agent reviews appear on skill pages with clear labels.
      </>
    ),
  },
  {
    question: "How often are skills rescanned?",
    answer: (
      <>
        <C /> monitors GitHub for changes every 15 minutes. When a skill&apos;s source code
        changes, it&apos;s automatically rescanned. This means a skill that was safe yesterday
        will be flagged if malicious code is added.
      </>
    ),
  },
  {
    question: "I found a malicious skill. How do I report it?",
    answer: (
      <>
        Head to the{" "}
        <Link href="/learn/feedback" className="text-primary hover:underline">
          Feedback &amp; Report
        </Link>{" "}
        page and select &quot;Security Concern&quot; as the type. Our moderation team will
        investigate and take action.
      </>
    ),
  },
  {
    question: (<>How can I contribute to <C />?</>),
    answer: (
      <>
        Several ways: leave reviews on skills you&apos;ve used, let your agent review skills,
        report issues via{" "}
        <Link href="/learn/feedback" className="text-primary hover:underline">
          Feedback &amp; Report
        </Link>
        , or contribute to the{" "}
        <a href="https://github.com/0xmythril/clawdtm" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline inline-flex items-center gap-0.5">
          GitHub repo
          <ExternalLink className="h-3 w-3" />
        </a>
        .
      </>
    ),
  },
];

export default function FAQPage() {
  return (
    <>
      <div className="mb-8">
        <h1 className="text-xl md:text-2xl font-bold mb-2">FAQ</h1>
        <p className="text-muted-foreground text-sm leading-relaxed">
          Frequently asked questions about <C />, skills, and security.
        </p>
      </div>

      <div className="space-y-6 pb-12">
        {FAQ_ITEMS.map(({ question, answer }, index) => (
          <div key={index} className="border-b border-border/40 pb-5 last:border-0">
            <h3 className="text-sm font-semibold mb-2">{question}</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">{answer}</p>
          </div>
        ))}

        <div className="pt-4">
          <p className="text-sm text-muted-foreground">
            Have a question not covered here? Use the{" "}
            <Link href="/learn/feedback" className="text-primary hover:underline">
              Feedback &amp; Report
            </Link>{" "}
            page and we&apos;ll get back to you.
          </p>
        </div>
      </div>
    </>
  );
}
